# Generated by Django 3.1.1 on 2020-10-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
